### ISSUE TITLE
Missing "create-call" endpoint for creating web calls

### ISSUE THREAD

**Issue by adiestel** [RetellAI/retell-typescript-sdk#116]
The sdk is missing the ability to call create-call endpoint for creating web calls. We need the create-call endpoint in order to use the new version of the client sdk.

I'd be willing to create a PR to add this in but since the api isn't documented anywhere that I can find I'm not 100% sure of what the details for the parameters would be.  Also it's naming sort of conflicts with the existing call.create function that is purely for creating phone calls and not web calls.

**Comment by AustinZzx** [comment]
We are working on adding the documentation and updating SDK for that. Should be finished within 2 days.

**Comment by AustinZzx** [comment]
https://docs.retellai.com/make-calls/web-call
https://docs.retellai.com/api-references/create-web-call

Docs updated, new server SDK released with the new spec. Appreciate the patience.
