### ISSUE TITLE
Adding support for polish language

### ISSUE THREAD

**Issue by Mhal007** [RetellAI/retell-typescript-sdk#162]
Hi guys, great project!

We just introduced Retell in our customer-facing product. Initially, we were offering english only, but the market demands support in our domestic language - Polish.

It seems like it is not supported in Retell, yet the voice providers' models do seem to operate in Polish.

Is it planned to be supported in the near future? Or maybe there is some kind of a workaround we could apply, or some custom solution on top that we could develop to make it possible?

Unfortunately, at this moment, it's a deal breaker for the business, and we will need to switch to a different provider if it isn't supported in Retell.

**Comment by AustinZzx** [comment]
It's supported now.
